.python_job_template:
  image: python:3.10
  interruptible: true

download_deps:
  extends: .python_job_template
  stage: download_deps
  before_script:
    - mkdir ~/.pip
    - python -m venv venv
    - source ./venv/bin/activate
  script:
    - pip install --no-cache-dir --upgrade pip
    - pip install --no-cache-dir setuptools_scm[toml]
    - curl -sSL https://pdm.fming.dev/install-pdm.py | python - --version v2.9.3
    - export PATH="/root/.local/bin:$PATH"
    - rm -f .pdm.toml
    - pdm config pypi.extra.url "$NEXUS_PYPI_PULL_URL"
    - pdm sync -G dev -L lockfiles/cpu.lock
  artifacts:
    paths:
      - "venv"
    expire_in: 2 hour
  rules:
    - if: $CI_COMMIT_BRANCH

.lint_test_template:
  extends: .python_job_template
  dependencies:
    - download_deps
  before_script:
    - source ./venv/bin/activate
  rules:
    - if: $CI_COMMIT_BRANCH

lint:
  extends: .lint_test_template
  stage: lint
  script:
    - deptry .
    - black . --check
    - ruff check .

test:
  extends: .lint_test_template
  stage: test
  script:
    - coverage run -m pytest tests/
    - coverage xml -o coverage.xml
    - coverage report -m --skip-covered
  artifacts:
    expire_in: 2 hour
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

stages:
  - download_deps
  - lint
  - test
