model_name: HuggingFaceH4/zephyr-7b-beta
transcript_path: data/harvard_transcript/philosophy_lecture.txt
output_path: experiments/2023-10-25_zero-shot-quiz-generation/results/metadata/metadata_zephyr_en_philosophy.json
connector:
  (): "quiz_generation.connectors.APIConnector"
  api_url: http://0.0.0.0:8000/generate
  cache_path: .cache_zephyr
language: en
prompts_config:
  (): "quiz_generation.metadata_generation.metadata_generator.MetadataPromptsConfig"
  summary_prompt_path: quiz_generation/metadata_generation/prompts/english/summary_prompt.txt
  title_prompt_path: quiz_generation/metadata_generation/prompts/english/title_prompt.txt
  description_prompt_path: quiz_generation/metadata_generation/prompts/english/description_prompt.txt
  generate_topics_prompt_path: quiz_generation/metadata_generation/prompts/english/generate_topics_prompt.txt
  combine_topics_prompt_path: quiz_generation/metadata_generation/prompts/english/combine_topics_prompt.txt
