resources:
    accelerators: T4:2

envs:
    MODEL_NAME: teknium/OpenHermes-2.5-Mistral-7B
    TOKENIZER: teknium/OpenHermes-2.5-Mistral-7B

run: |
    git clone https://github.com/vllm-project/vllm.git
    cd vllm
    pip install .
    cd ..
    python -m vllm.entrypoints.api_server \
        --model $MODEL_NAME \
        --tensor-parallel-size 2 \
        --tokenizer $TOKENIZER \
        --dtype float16
