model_name: gpt-4-1106-preview
connector:
  (): "aristote.connectors.connectors.CustomOpenAIConnector"
  cache_path: .cache_gpt-4-2
  max_requests_per_second: 50
metadata_path: results/metadata_gpt-35_fr_cs_ri.json
quizzes_path: results/quizzes_gpt-35_fr_cs_ri.jsonl
language: fr
prompts_config:
  (): "aristote.evaluation.evaluator.EvaluationPromptsConfig"
  is_related_prompt: aristote/evaluation/prompts/zephyr/question_is_related_prompt.txt
  is_self_contained_prompt: aristote/evaluation/prompts/zephyr/question_is_self_contained_prompt.txt
  is_question_prompt: aristote/evaluation/prompts/zephyr/question_is_question_prompt.txt
  language_is_clear_prompt: aristote/evaluation/prompts/zephyr/question_has_clear_language_prompt.txt
  answers_are_all_different_prompt: aristote/evaluation/prompts/zephyr/answers_are_all_different_prompt.txt
  fake_answers_are_not_obvious_prompt: aristote/evaluation/prompts/zephyr/fake_answers_are_not_obvious_prompt.txt
  answers_are_related: aristote/evaluation/prompts/zephyr/answers_are_related_prompt.txt
  quiz_about_concept: aristote/evaluation/prompts/zephyr/quiz_about_concept_prompt.txt
output_path: results/evaluated_quizzes_gpt35_fr_ri.jsonl
