model_name: gpt-4-1106-preview
transcript_path: data/cs_videos_transcripts/transcript_ri.json
connector:
  (): "quiz_generation.connectors.connectors.CustomOpenAIConnector"
  cache_path: .cache_gpt-4
  max_requests_per_second: 30
metadata_path: experiments/2023-10-25_zero-shot-quiz-generation/results/metadata/metadata_gpt-4_fr_cs_ri.json
language: fr
prompts_config:
  (): "quiz_generation.quiz_generation.quiz_generator.QuizPromptsConfig"
  quiz_generation_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_generation_prompt.txt
  quiz_evaluation_prompts_config:
    (): "quiz_generation.quiz_generation.quiz_generator.QuizEvaluationPromptsConfig"
    is_related_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_evaluation_prompts/question_is_related_prompt.txt
    is_self_contained_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_evaluation_prompts/question_is_self_contained_prompt.txt
    is_question_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_evaluation_prompts/question_is_question_prompt.txt
    language_is_clear_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_evaluation_prompts/question_has_clear_language_prompt.txt
    answers_are_all_different_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_evaluation_prompts/answers_are_all_different_prompt.txt
    fake_answers_are_not_obvious_prompt: quiz_generation/quiz_generation/prompts/zephyr/quiz_evaluation_prompts/fake_answers_are_not_obvious_prompt.txt
output_path: experiments/2023-10-25_zero-shot-quiz-generation/results/quizzes/quizzes_gpt-4_fr_cs_ri.jsonl